services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: orderflow
      POSTGRES_PASSWORD: orderflow
      POSTGRES_DB: order_flow
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - app-network

  api:
    build:
      context: ./OrderFlow.API
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_URLS=http://+:5000
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=order_flow;Username=orderflow;Password=orderflow
    depends_on:
      - db
    networks:
      - app-network

  blazor:
    build:
      context: ./OrderFlow
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - api
    environment:
      - ApiUrl=http://api:5000
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
